#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 11 19:24:20 2021

@author: wmorland

Script to monitor the external power to the UPS and shut the Pi down gracefully
if it is disconnected.  External power is checked once every five seconds.

This script is automatically run as root whenever the Pi is rebooted.

Schedule can be reviewed in sudo crontab -e

The following lines are added to the crontab file by the install script.
Actual paths are specified in install.cfg

PYTHONPATH=/opt/RKR-Logger
RKRPROCESSLOGS=/home/pi/RKR-process-logs
@reboot root power-monitor &
"""
from time import sleep
import os
import subprocess
import logging
import ups_lite


def main():
    logger = logging.getLogger('power-monitor')
    logger.info('Start external power monitoring.')
    ups = ups_lite.UPS()
    logger.info(f'UPS Voltage: {ups.voltage():1.2f}')
    logger.info(f'UPS Capacity: {int(ups.capacity()):03d}%')

    try:
        while True:
            sleep(5)
            if not ups.external_power():
                logger.info('External power disconnected.')
                logger.info(f'UPS Voltage: {ups.voltage():1.2f}')
                logger.info(f'UPS Capacity: {int(ups.capacity()):03d}%')
                logger.info('Starting shutdown process.')

                # Any actions we need to take before shutdown go here

                try:
                    subprocess.run('halt', check=True)
                except subprocess.CalledProcessError as process_error:
                    rc = process_error.returncode
                    logger.error(f'Shutdown failed. return code = {rc}')
                    return rc
                logger.info('Shutdown process started successfully.')
                return 0
    except KeyboardInterrupt:
        logger.info('Interupted and terminated.')
        return 0


if __name__ == '__main__':
    log_dir = os.getenv('RKRPROCESSLOGS')
    log_name = f'{log_dir}/power-monitor.log'
    if os.path.exists(log_name):
        os.rename(log_name, f'{log_name}.old')
    logging.basicConfig(filename=log_name, filemode='w', level=logging.INFO)
    main()
    logging.shutdown()
