#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  2 20:16:19 2021

@author: wmorland
"""


import os
import logging
import nmea
import can
from time import sleep


def main():
    """
    Periodically send a message to the CAN Bus.

    Returns
    -------
    None.

    """
    logger = logging.getLogger('can-send')
    logger.info('*** can-send ***')

    can0 = nmea.start_can_bus()

# Rudder
# 2,127245,15,255,8,ff,ff,ff,7f,e1,fe,ff,ff
# Position Rapid Update
# 2,129025,9,255,8,2f,26,ff,19,cb,0e,a0,d0
# GNS Position Data
# 3,129029,9,255,8,20,2b,7a,6d,48,40,95,79
# 3,129029,9,255,8,21,2e,80,cc,ff,52,da,85
# 3,129029,9,255,8,22,0d,06,00,17,f8,2e,2a
# 3,129029,9,255,8,23,3e,f8,f4,00,bb,3d,02
# 3,129029,9,255,8,24,00,00,00,00,10,fc,0c
# 3,129029,9,255,8,25,46,00,8c,00,4b,f2,ff
# 3,129029,9,255,8,26,ff,ff,ff,ff,ff,ff,ff


    rudder_msg = can.Message(arbitration_id=0b010_01_11110001_00001101_00001111,
                             data=[0xff, 0xff, 0xff, 0x7f, 0xe1, 0xfe, 0xff, 0xff],
                             extended_id=True)
    logger.info('Starting loop to repeated send CAN messages until interupt.')
    try:
        while True:
            can0.send(rudder_msg)
            sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        nmea.stop_can_bus()
        logger.info('Loop interupted.')

    logger.info('*** can-send ***')


if __name__ == '__main__':
    log_dir = os.getenv('RKRPROCESSLOGS')
    log_name = f'{log_dir}/can-send.log'
    if os.path.exists(log_name):
        os.rename(log_name, f'{log_name}.old')
    logging.basicConfig(filename=log_name, filemode='w', level=logging.INFO)
    main()
    logging.shutdown()
