#!/usr/bin/python3
'''
Rum Kist Racing NMEA2000 Logger install script.

@Author - Bill Morland
@Version 1.0

Error codes
2 - script was called with an unrecognised parameter
3 - unable to establish a connection to Github
'''

import sys
import getopt
import os
import wget
import logging

logging.basicConfig(level=logging.INFO)
logging.info('*** Installing Rum Kist Racing NMEA2000 Logger ***')
logging.info('*** Start install-RKR-Logger ***')

DIRECTORY = '/home/pi/RKR-Logger'
PROJECT = 'https://raw.githubusercontent.com/Bill374/2000-sail-polars/'
BRANCH = 'main'
USAGE = 'install-RKR-Logger [-d <install directory>] [-b <Github branch>]'

directory = DIRECTORY
branch = BRANCH

# Parse the arguments passed to the script
try:
    opts, args = getopt.getopt(sys.argv[1:], 'hd:b:', ['help'])
except getopt.GetoptError:
    logging.error('Unexpected argument.')
    logging.info(USAGE)
    sys.exit(2)

for opt, arg in opts:
    if opt in ("-h", "--help"):
        print(USAGE)
        sys.exit(0)
    elif opt == '-d':
        directory = arg
    elif opt == '-b':
        branch = arg

# A good check to include here before executing anything else is to find out
# if this is the latest version of install-rkr-logger
# If this is not the latest version should we terminate? Fetch the
# latest version?

# Make sure we have a nice clean empty directory for our install
# logging.info(f'Installing to directory: {directory}')
# if os.path.isdir(directory):
#     logging.info('Installation directory already exists deleting directory '
#                  'and contents.')
#     os.system(f'rm -rf {directory}')
# elif os.path.isfile(directory):
#     logging.info('A file that is not a directory exists with the name '
#                  f'{directory}.  Removing file')
#     os.system(f'rm {directory}')
# logging.info(f'Creating directory: {directory}')
# os.system(f'mkdir {directory}')
logging.info('Change working directory to install directory')
os.chdir(directory)
if directory != os.getcwd():
    logging.error(f'Not in the expected directory {directory}')
    sys.exit(-1)
logging.info(f'Install directory: {directory}')

# download the real installer that does all the work from GitHub
logging.info(f'Installing from Github branch: {branch}')

# Path to the Github repository
git_hub_url = (f'{PROJECT}{BRANCH}/')
logging.info(f'Downloading from: {git_hub_url}')

# Get the real installer and install.cfg
try:
    file_to_get = f'{git_hub_url}Installation/pi_install.py'
    logging.info(f'Copying {file_to_get}')
    fileName = wget.download(file_to_get, out=directory)
    logging.info(f'Copying {file_to_get}: SUCCESS')
    logging.info(f'{fileName}')
    file_to_get = f'{git_hub_url}Installation/install.cfg'
    logging.info(f'Copying {file_to_get}')
    fileName = wget.download(file_to_get, out=directory)
    logging.info(f'Copying {file_to_get}: SUCCESS')
    logging.info(f'{fileName}')
except Exception as http_error:
    logging.error(f'Copying {file_to_get}: FAIL')
    logging.error(http_error)
    sys.exit(-1)

import pi_install
rc = pi_install.main(git_hub_url)

if rc != 0:
    logging.error('Something went wrong in main-install')
    sys.exit(rc)

logging.info('*** End install-RKR-Logger ***')

sys.exit(0)
