#!/usr/bin/python3
'''
Rum Kist Racing NMEA2000 Logger Install script.

This is the real installer that does all the work.
Called from install-RKR-Logger.
'''
# Required for parsing command line
import sys
import getopt
# Required for accessing O/S filesystem
import os
# Required for downloading files
import wget
# Required for chmod permissions
# import stat
# Required for testing existance of a file on Github
import urllib3
import logging
import pi_install as pi


# Initialise installation messaging
VERBOSE = False

# Parse the arguments passed to the script
# If any of them are not recognised exit with an error
# Since this script downloads and runs the the main-install which might need
# more parameters.  It might be better if it did not terminate for unknown
# parameters and just leave that to the main installer.
# We can make that decision later.
try:
    opts, args = getopt.getopt(sys.argv[1:], "vg:", ["verbose"])
except getopt.GetoptError as err:
    # Something went wrong, found an unexpected argument
    print(err)
    print('Unexpected parameter - terminating main-install')
    sys.exit(2)

GIT_HUB_URL = 'https://raw.githubusercontent.com/Bill374/'\
    '2000-sail-polars/master/'

for opt, arg in opts:
    if opt == '-v':
        VERBOSE = True
        logging.info('option -v')
    elif opt == '-g':
        GIT_HUB_URL = arg
        logging.info('option -g' + arg)

logging.info('*** Start main-install ***')

directory = os.getcwd()

logging.info('installing from ' + GIT_HUB_URL)
logging.info('installing to ' + directory)

# download all the files listed in the manifest file
logging.info('Retrieving manifest of files to install')
fileName = wget.download(GIT_HUB_URL + 'Installation/manifest.txt')
logging.info('')
logging.info('downloaded ' + fileName)
manifest = open('manifest.txt', 'r')
http = urllib3.PoolManager()
for source in manifest:
    if source[0] != '#':
        fileToGet = GIT_HUB_URL + source.strip('\n')
        try:
            req = http.request('GET', fileToGet)
        except urllib3.exceptions.HTTPError as http_error:
            logging.info('unable to find file ' + source.strip('\n') +
                         ' listed in manifest')
            logging.info(http_error)
            sys.exit(3)
        fileName = wget.download(fileToGet, out=directory)
        logging.info('')
        logging.info('downloaded ' + fileName)
manifest.close()

# install apt dependencies
logging.inf('Installing apt dependencies')
rc = os.system('apt-get update')
rc = os.system('apt-get install -y can-utils')

# install python packages
rc = os.system('pip3 install --upgrade python-can')

# modify /boot/config.txt if required
bootCfg = []
bootCfg.append(pi.CfgLine('# Waveshare RS485 CAN HAT mcp2515 kernel driver\n'))
bootCfg.append(pi.CfgLine('dtparam=spi=on\n'))
# RS485 CAN HAT - 12M crystal version
bootCfg.append(pi.CfgLine('dtoverlay=mcp2515-can0,oscillator=12000000,'
                          'interrupt=25,spimaxfrequency=2000000\n'))

pi.add_lines('/boot/config.txt', bootCfg)


logging.info('*** End main-install ***')

# Clean Exit
sys.exit(0)
